Updated to work with node 6
AssertionError: Current node version is not supported for development, expected "6.2.2" to satisfy "4.x || 5.x".

After patch tested with node 6.2.2 all seems to work well . .